---
- name: "Build Hub Collection"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create build directory
      ansible.builtin.tempfile:
        state: directory
        suffix: build
      register: builddir

    - name: Copy build code
      ansible.posix.synchronize:
        src: ./
        dest: "{{ builddir.path }}"
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=venv"
          - "--exclude=.tox"
          - "--exclude=.ruff_cache"
          - "--exclude=*.gz"

    - name: Create Hub Galaxy by merging galaxy.hub.yml
      ansible.builtin.copy:
        dest: "{{ builddir.path }}/galaxy.yml"
        mode: "0644"
        content: "{{
          lookup('ansible.builtin.file', builddir.path + '/galaxy.yml') | from_yaml
          | combine(lookup('ansible.builtin.file', builddir.path + '/galaxy.hub.yml') | from_yaml,
                    recursive=True)
          | to_nice_yaml }}"

    - name: Replace usage in README.md
      ansible.builtin.replace:
        path: "{{ builddir.path }}/README.md"
        regexp: 'redhatinsights\.eda\.insights'
        replace: 'redhat.insights_eda.insights'

    - name: Replace requirements install in README.md
      ansible.builtin.replace:
        path: "{{ builddir.path }}/README.md"
        regexp: '/ansible_collections/redhatinsights/eda/'
        replace: '/ansible_collections/redhat/insights_eda/'

    - name: Inject Support section into README.md
      ansible.builtin.blockinfile:
        path: "{{ builddir.path }}/README.md"
        insertbefore: "## Contributing"
        marker: ""
        block: |
          ## Support

          This collection is maintained by the Red Hat Insights team.

          As Red Hat Ansible Certified Content, this collection is entitled to
          support through the Ansible Automation Platform (AAP) using the
          **Create issue** button on the top right corner of the collection page
          on Red Hat Ansible Automation Hub.

          If a support case cannot be opened with Red Hat and the collection has
          been obtained either from Galaxy or GitHub, community help may be
          available on the [Ansible Forum](https://forum.ansible.com/).

    - name: Build collection
      ansible.builtin.command: 'ansible-galaxy collection build "{{ builddir.path }}"'
      register: collection_build
      changed_when: collection_build.rc != 0
